export const Codes = {
  UBICATION_WEB: 'WEB',
  UBICATION_APP: 'APP',
  UBICATION_TYPE_BILLBOARD: 'BILLBOARD',
  UBICATION_TYPE_NATIVE_ADVERTISING: 'NATIVE_ADVERTISING',
  UBICATION_TYPE_SKIN: 'SKIN',
  UBICATION_TYPE_SPONSOR: 'SPONSOR',
  PAGE_STREAMING: 'STREAMING',
  PAGE_SCHEDULE: 'SCHEDULE',
  PAGE_STREAMING_NEW: 'STREAMING_NEW',
}